In [1]:
# Import the numpy package
import numpy as np

# Create a simple array
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [4]:
import numpy as np

# 1. Создание массивов
one_d_array = np.arange(1, 6)  # одномерный массив от 1 до 5
two_d_array = np.arange(1, 7).reshape(2, 3)  # двумерный массив от 1 до 6, 2 строки и 3 столбца

# Вывод массивов
print("Одномерный массив:")
print(one_d_array)
print("\nДвумерный массив:")
print(two_d_array)

# 2. Проверка атрибутов
print("Атрибуты одномерного массива:")
print("Форма (shape):", one_d_array.shape)
print("Размер (size):", one_d_array.size)
print("Тип данных (dtype):", one_d_array.dtype)

print("\nАтрибуты двумерного массива:")
print("Форма (shape):", two_d_array.shape)
print("Размер (size):", two_d_array.size)
print("Тип данных (dtype):", two_d_array.dtype)

# 3. Создание массива с числами от 1 до 3 и типом float
float_array = np.arange(1, 4, dtype=float)
print("\nМассив с типом float:")
print(float_array)
print("Тип данных (dtype):", float_array.dtype)

temperatures = np.array([28, 30, 29, 31, 27, 26, 30])
print("Температуры за неделю:", temperatures)

random_array = np.random.randint(1, 11, size=(2, 5))  # 2 строки, 5 столбцов
print("\nСлучайный массив 2x5 от 1 до 10:")
print(random_array)

pixels = np.random.randint(0, 256, size=(3, 3, 3), dtype=np.uint8)
print("\nТрёхмерный массив пикселей RGB (3x3 изображение):")
print(pixels)


Одномерный массив:
[1 2 3 4 5]

Двумерный массив:
[[1 2 3]
 [4 5 6]]
Атрибуты одномерного массива:
Форма (shape): (5,)
Размер (size): 5
Тип данных (dtype): int32

Атрибуты двумерного массива:
Форма (shape): (2, 3)
Размер (size): 6
Тип данных (dtype): int32

Массив с типом float:
[1. 2. 3.]
Тип данных (dtype): float64
Температуры за неделю: [28 30 29 31 27 26 30]

Случайный массив 2x5 от 1 до 10:
[[10  2 10  4  1]
 [ 1  6  5  2  6]]

Трёхмерный массив пикселей RGB (3x3 изображение):
[[[128 108 191]
  [168  64  37]
  [105  38 202]]

 [[217  11 124]
  [133 252 194]
  [ 39 148  54]]

 [[ 81 163  58]
  [202  34  17]
  [222 154 115]]]


In [10]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)


array_4d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("Shape:", array_4d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_4d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_4d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int32
Shape: (4, 4)
Size: 16
Data Type: int32


In [11]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [15]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Slice of the array: [[2 3]
 [5 6]]


In [17]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array


Result of Boolean Indexing: [4 5 6]


In [18]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

First element: 10
First three elements: [10 20 30]


In [28]:
import numpy as np

# Creating a sample array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(array[4]) 

print("Slice of the array:", array[2:8])

print(array[[1, 3, 5]])


5
Slice of the array: [3 4 5 6 7 8]
[2 4 6]


In [24]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print(array[array > 30])


[40 50]


In [ ]:
import numpy as np

arr1 = np.arange(1, 11)  # [1, 2, ..., 10]
arr1[4] = 50  # fifth element (index 4)
print("Modified array:", arr1)

In [30]:
import numpy as np

arr2 = np.arange(10)  # [0, 1, ..., 9]
arr2[3:8] = -arr2[3:8]
print("Negative slice:", arr2)


Negative slice: [ 0  1  2 -3 -4 -5 -6 -7  8  9]


In [31]:
arr3 = np.random.randint(1, 101, size=20)
arr3[arr3 > 50] = -1
print("Modified with condition (values > 50 set to -1):", arr3)


Modified with condition (values > 50 set to -1): [ 5 -1 -1 38 -1 -1 22 36 -1 -1  4 -1 -1 -1 -1 -1 -1 35  4 -1]


In [32]:
arr4 = np.random.randint(1, 10, size=(5, 5))
print("Original 2D array:\n", arr4)

# Multiply diagonal elements by 2
indices = np.arange(5)
arr4[indices, indices] *= 2
print("Diagonal doubled:\n", arr4)


Original 2D array:
 [[7 8 7 1 2]
 [8 4 1 4 5]
 [3 3 2 4 6]
 [8 9 3 5 7]
 [9 3 3 3 4]]
Diagonal doubled:
 [[14  8  7  1  2]
 [ 8  8  1  4  5]
 [ 3  3  4  4  6]
 [ 8  9  3 10  7]
 [ 9  3  3  3  8]]


In [33]:
arr5 = np.arange(10)
slice_view = arr5[2:6]  # slice is a view, not a copy!
slice_view[0] = 999
print("Modified slice:", slice_view)
print("Original array after slice modification:", arr5)


Modified slice: [999   3   4   5]
Original array after slice modification: [  0   1 999   3   4   5   6   7   8   9]
